# Generated by Django 5.1.4 on 2026-08-23 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_items',
                'ordering': ['category', 'label'],
                'indexes': [models.Index(fields=['year'], name='budget_item_year_3bbdf9_idx')],
            },
        ),
    ]
