# Generated by Django 4.2 on 2026-09-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventpartner_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpartner',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventpartner',
            unique_together={('event', 'email')},
        ),
    ]
