# Generated by Django 5.1.4 on 2026-08-23 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DUE', 'Due'), ('EVENT_REVENUE', 'Event Revenue'), ('EVENT_COST', 'Event Cost'), ('GIFT', 'Gift'), ('OTHER_INCOME', 'Other Income'), ('OTHER_EXPENSE', 'Other Expense')], max_length=32)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occurred_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='events.event')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['type'], name='transaction_type_840495_idx'), models.Index(fields=['event'], name='transaction_event_i_7794da_idx'), models.Index(fields=['occurred_at'], name='transaction_occurre_80a5a2_idx')],
            },
        ),
    ]
