# Generated by Django 5.1.4 on 2026-08-23 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_to', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=64, unique=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='ledger.transaction')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
    ]
