# Generated by Django 5.1.4 on 2026-08-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE_OFFICER', 'Finance Officer'), ('COMMITTEE_MEMBER', 'Committee Member'), ('STUDENT', 'Student')], default='COMMITTEE_MEMBER', max_length=32),
        ),
    ]
